name: Example
on:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Checkout action
        uses: actions/checkout@v2
        with:
          repository: EffortGames/action-template
          token: ${{ steps.generate_token.outputs.token }}
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Create README.md
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "github.json:"
          echo "$GITHUB_CONTEXT" | tee github.json
          pip install -r requirements.txt
          ./main.py README.md.template github.json .github/workflows/example.yml > README.md
          git add README.md
          git commit -am"Update README.md"
          git push origin master
